window.shiftPageConfig = {
  type: "CLOSING",
  title: "Closing Shift",
  subtitle: "Secure today's operation and prepare tomorrow's priorities.",
  checklist: [
    ["End of Service", "Finish service cleanly and account for guest needs.", [["service-ended", "Confirm service has ended appropriately", "Verify the service period is complete."], ["outstanding-orders", "Review outstanding guest orders", "Close or hand off remaining orders."], ["guest-concerns", "Verify remaining guest concerns are addressed", "Ensure every concern has an owner."]]],
    ["Closing Assignments", "Confirm the team has completed closing responsibilities.", [["closing-responsibilities", "Confirm closing responsibilities", "Review the closing assignment plan."], ["cleaning-tasks", "Verify assigned cleaning tasks", "Confirm assigned work is complete."], ["employee-responsibilities", "Review incomplete employee responsibilities", "Capture anything that needs follow-up."]]],
    ["Cleaning & Facility", "Leave the restaurant ready for the next day.", [["foh-cleaning", "Verify front-of-house cleaning", "Check guest-facing areas."], ["production-cleaning", "Verify production-area cleaning", "Check kitchen and production areas."], ["storage-cleaning", "Verify storage areas", "Leave storage clean and organized."], ["restrooms", "Verify restrooms", "Confirm cleanliness and supplies."], ["facility-walkthrough", "Complete final facility walkthrough", "Check the restaurant before securing it."]]],
    ["Product & Inventory", "Document carry-forward concerns without duplicating Inventory.", [["ending-stock", "Review critical ending stock", "Identify products needing attention."], ["known-shortages", "Record known shortages", "Capture tomorrow's product risks."], ["product-storage", "Confirm product storage", "Verify products are stored correctly."], ["waste-entries", "Review waste entries", "Confirm known waste is documented."], ["next-day-products", "Identify products requiring next-day attention", "Create follow-up where needed."]]],
    ["Equipment", "Secure equipment and record problems.", [["equipment-shutdown", "Verify equipment shutdown where required", "Follow operating shutdown requirements."], ["refrigeration", "Confirm refrigeration remains operational", "Protect product overnight."], ["equipment-issues", "Review equipment Issues", "Confirm equipment follow-up is owned."], ["report-equipment", "Report newly discovered equipment problems", "Use Report Issue for new problems."]]],
    ["Operational Follow-Up", "Leave a clear operational carry-forward.", [["unresolved-issues", "Review all unresolved Issues", "Confirm open Issues have next steps."], ["pending-tasks", "Review pending Tasks", "Confirm pending work is owned."], ["overdue-tasks", "Review overdue Tasks", "Address work that missed its due time."], ["next-day-tasks", "Create required next-day Tasks", "Use Create Task for follow-up."]]],
    ["Next-Day Preparation", "Set tomorrow up for a strong start.", [["staffing-concern", "Identify next-day staffing concern", "Capture staffing risks."], ["product-concern", "Identify next-day product concern", "Capture product risks."], ["equipment-concern", "Identify next-day equipment concern", "Capture equipment risks."], ["tomorrow-priority", "Set tomorrow's operational priority", "Write the priority below."]]]
  ]
};
