window.shiftPageConfig = {
  type: "MID_SHIFT",
  title: "Mid-Shift",
  subtitle: "Maintain service readiness and address active operational exceptions.",
  checklist: [
    ["Shift Review", "Keep active service priorities visible.", [["open-issues", "Review open operational Issues", "Confirm ownership and next action."], ["pending-tasks", "Review pending Tasks", "Check active and overdue follow-up."], ["today-priority", "Review today's priority", "Align the team on the next operational priority."]]],
    ["Staffing & Deployment", "Keep the floor and stations covered.", [["staffing-coverage", "Confirm current staffing coverage", "Verify coverage through the service period."], ["callouts", "Review call-outs / early departures", "Record changes affecting deployment."], ["critical-positions", "Confirm critical positions", "Make sure essential positions remain covered."], ["break-coverage", "Verify break coverage", "Protect service while breaks are taken."], ["position-deployment", "Adjust position deployment if necessary", "Move coverage where operations need it most."]]],
    ["Peak Readiness", "Maintain readiness during active operation.", [["peak-period", "Review upcoming peak period", "Prepare for the next volume increase."], ["production-readiness", "Confirm production readiness", "Verify production can support demand."], ["stations-stocked", "Verify service stations are stocked", "Replenish essential service supplies."], ["team-priorities", "Confirm team understands current priorities", "Close the loop with the team."]]],
    ["Product & Inventory", "Review availability without duplicating Inventory.", [["product-availability", "Review critical product availability", "Identify products at risk."], ["shortages", "Identify shortages", "Record shortages as checklist exceptions."], ["prep-levels", "Verify prep levels", "Confirm preparation supports service."], ["operating-supplies", "Check essential operating supplies", "Check supplies needed for the shift."]]],
    ["Guest Experience", "Protect the guest experience during service.", [["service-conditions", "Review current service conditions", "Scan service flow and guest impact."], ["guest-areas", "Check guest areas", "Confirm guest-facing areas remain ready."], ["restrooms", "Verify restrooms", "Confirm cleanliness and supplies."], ["guest-concerns", "Review active guest concerns", "Ensure concerns have owners and next steps."]]],
    ["Equipment & Facility", "Keep critical systems operational.", [["critical-equipment", "Verify critical equipment remains operational", "Check equipment currently supporting service."], ["equipment-problems", "Review equipment problems", "Confirm known problems have follow-up."], ["facility-condition", "Check restaurant/facility condition", "Address conditions affecting operations."]]],
    ["Follow-Up", "Close the loop on active operational work.", [["unresolved-issues", "Review unresolved Issues", "Confirm open Issues are moving forward."], ["overdue-tasks", "Review overdue Tasks", "Reassign or address overdue work."], ["next-priority", "Confirm next operational priority", "Name the most important next action."]]]
  ]
};
